version: '3.18'

networks:
  mynet:
    driver: bridge

services:
  conteiner-dev:
    build:
      context: .
      dockerfile: Dockerfile.remote
    container_name: container_dev
    networks:
      - mynet
    volumes:
      - ".:/app"
    ports:
      - "8082:8082"
  app:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    networks:
      - mynet
    ports:
      - "8085:8080"
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynet